### ISSUE TITLE
Resize The SideBar

### ISSUE THREAD

**Issue by VFA250** [ZTL-UwU/shadcn-docs-nuxt-starter#2]
In this project, what file or files should I put in order to change the size of the sidebar where the articles and categories are grouped, such as so that the titles do not appear as three dots for texts with long titles?
![CleanShot 2024-12-01 at 11 08 54](https://github.com/user-attachments/assets/74ecce98-154e-4952-956f-2caf40f107e9)

**Comment by ZTL-UwU** [comment]
https://github.com/ZTL-UwU/shadcn-docs-nuxt/issues/61

**Comment by VFA250** [comment]
Brother! Thank you very much!
